                     OBJECTIVE
THE MAIN IDEA OR OBJECTIVE OF THIS PROJECT IS: 
1. TO PREDICT THAT USER WILL PURCHASE THE PRODUCT OR NOT, BY TAKING INPUT(AGE AND ESTIMATED SALARY)
2. CHECKING THE ACCURACY OF THIS PROJECT BY USING DIFFERENT CLASSIFICATION ALGORITHM

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.iloc[:,2:4]

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [4]:
data.iloc[:,2:4].values

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [5]:
x=data.iloc[:,2:4].values

In [6]:
x.shape

(400, 2)

In [7]:
data.iloc[:,-1]

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
data.iloc[:,-1].values

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
y=data.iloc[:,-1].values

In [10]:
y.shape

(400,)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)

In [12]:
x_train.shape

(280, 2)

In [13]:
x_test.shape

(120, 2)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [15]:
x_train=scaler.fit_transform(x_train)
x_train

array([[-1.54139384, -1.552204  ],
       [-0.88103714,  0.16232128],
       [-0.03200709, -0.25879019],
       [-0.3150171 ,  0.07208311],
       [-1.16404715,  0.34279763],
       [-1.82440386, -1.46196583],
       [-0.12634376,  2.23779926],
       [ 1.00569631, -1.25141009],
       [ 1.85472636,  0.7639091 ],
       [-0.3150171 , -0.25879019],
       [ 0.62834962,  0.28263885],
       [ 0.25100293, -0.31894897],
       [-1.54139384, -1.28148948],
       [-0.12634376, -0.43926653],
       [ 0.25100293,  0.07208311],
       [ 1.85472636,  0.94438545],
       [ 0.81702297, -1.07093375],
       [-1.06971048, -0.34902836],
       [-0.3150171 , -0.77013984],
       [ 0.15666626, -0.67990166],
       [-1.82440386, -1.52212461],
       [-0.69236379, -0.10839323],
       [-0.69236379,  0.19240068],
       [-0.3150171 ,  2.32803744],
       [-0.50369045, -1.16117192],
       [-0.40935377,  0.07208311],
       [ 2.04339971,  1.15494119],
       [-0.88103714,  2.35811683],
       [ 0.72268629,

In [16]:
x_test=scaler.transform(x_test)
x_test

array([[ 0.62834962, -1.43188644],
       [-0.3150171 , -1.49204522],
       [-0.97537381, -0.31894897],
       [-1.06971048,  0.61351215],
       [-0.3150171 , -1.28148948],
       [ 0.81702297, -0.61974288],
       [-1.16404715, -1.64244217],
       [ 0.3453396 ,  2.38819622],
       [ 0.3453396 ,  1.03462362],
       [-1.63573051,  0.07208311],
       [ 0.06232959,  0.28263885],
       [-1.73006719,  0.37287702],
       [ 0.06232959, -0.25879019],
       [-0.69236379, -1.552204  ],
       [ 0.81702297, -0.5595841 ],
       [-0.03200709,  1.27525875],
       [-0.59802712,  2.41827561],
       [ 0.06232959, -0.83029862],
       [ 1.47737967, -1.31156887],
       [-1.25838383,  0.28263885],
       [-0.22068043,  2.23779926],
       [-0.3150171 , -1.40180705],
       [ 0.25100293, -0.19863141],
       [-0.3150171 ,  0.82406789],
       [-0.12634376,  2.29795805],
       [-0.3150171 , -0.34902836],
       [-0.3150171 , -0.13847262],
       [ 0.43967628,  1.7866084 ],
       [ 0.15666626,

1.BY USING KNN

In [17]:
#CALCULATING VALUES OF K
np.sqrt(x_train.shape[0])

16.73320053068151

In [18]:
k=16

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=k)

In [20]:
#TRAIN OUR MODEL
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=16)

In [21]:
y_pred=knn.predict(x_test)

In [22]:
y_pred.shape

(120,)

In [23]:
y_test.shape

(120,)

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9166666666666666

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)


array([[73,  5],
       [ 5, 37]], dtype=int64)

In [26]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred)

0.8809523809523809

In [27]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

0.8809523809523809

In [28]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8809523809523809

In [29]:
def predict_output():
    age=int(input('ENTER YOUR AGE='))
    salary=int(input('ENTER YOUR SALARY='))
    
    x_new=np.array([[age],[salary]]).reshape(1,2)
    x_new=scaler.transform(x_new)
    
    if knn.predict(x_new)[0]==0:
        return "will not purchase"
    else:
        return "will purchase"

In [30]:
predict_output()

ENTER YOUR AGE=23
ENTER YOUR SALARY=40000


'will not purchase'

2. BY USING DECISION TREE CLASSIFIER ALGORITHM

In [52]:
from sklearn.tree import DecisionTreeClassifier
DTC= DecisionTreeClassifier(criterion='entropy', random_state=0)  
DTC.fit(x_train, y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [53]:
y_pred= DTC.predict(x_test)

In [54]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0], dtype=int64)

In [55]:
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test, y_pred) 

array([[72,  6],
       [ 7, 35]], dtype=int64)

In [56]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred)

0.8536585365853658

In [57]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

0.8333333333333334

In [58]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8433734939759037

In [59]:
def predict_output():
    age=int(input('ENTER YOUR AGE='))
    salary=int(input('ENTER YOUR SALARY='))
    
    x_new=np.array([[age],[salary]]).reshape(1,2)
    x_new=scaler.transform(x_new)
    
    if DTC.predict(x_new)[0]==0:
        return "will not purchase"
    else:
        return "will purchase"

In [60]:
predict_output()


ENTER YOUR AGE=23
ENTER YOUR SALARY=40000


'will not purchase'

3. RANDOM FOREST ALGORITHM

In [61]:
from sklearn.ensemble import RandomForestClassifier  
RFC= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
RFC.fit(x_train, y_train) 

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [64]:
y_pred= RFC.predict(x_test)

In [67]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [68]:
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test, y_pred) 

array([[71,  7],
       [ 4, 38]], dtype=int64)

In [69]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred)

0.8444444444444444

In [70]:
from sklearn.metrics import recall_score
recall_score(y_test,y_pred)

0.9047619047619048

In [71]:
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8735632183908046

In [73]:
def predict_output():
    age=int(input('ENTER YOUR AGE='))
    salary=int(input('ENTER YOUR SALARY='))
    
    x_new=np.array([[age],[salary]]).reshape(1,2)
    x_new=scaler.transform(x_new)
    
    if RFC.predict(x_new)[0]==0:
        return "will not purchase"
    else:
        return "will purchase"

In [75]:
predict_output()

ENTER YOUR AGE=27
ENTER YOUR SALARY=150000


'will purchase'